# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pr:
  autoCancel: true

trigger:
  batch: true
  branches:
    include:
      - master

variables:
  buildConfiguration: 'Release'

jobs:
- job: BuildAndTest
  displayName: "Build and test"
  strategy:
    matrix:
      windows:
        imageName: "windows-latest"
      linux:
        imageName: "ubuntu-latest"
      macOS:
        imageName: "macOS-latest"
  pool:
    vmImage: $(imageName)
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '10.0.x'
      includePreviewVersions: true
  - task: UseDotNet@2
    inputs:
      packageType: 'runtime'
      version: '8.0.x'
  - task: UseDotNet@2
    inputs:
      packageType: 'runtime'
      version: '6.0.x'
  - task: DotNetCoreCLI@2
    displayName: "dotnet build"
    inputs:
      command: 'build'
  - task: DotNetCoreCLI@2
    displayName: "dotnet test net10.0"
    inputs:
      command: 'test'
      arguments: '--framework net10.0 --no-build'
      projects: |
        **/*Tests.csproj
      publishTestResults: true
  - task: DotNetCoreCLI@2
    displayName: "dotnet test net8.0"
    inputs:
      command: 'test'
      arguments: '--framework net8.0 --no-build'
      projects: |
        **/*Tests.csproj
      publishTestResults: true
  - task: DotNetCoreCLI@2
    displayName: "dotnet test net6.0"
    inputs:
      command: 'test'
      arguments: '--framework net6.0 --no-build'
      projects: |
        **/*Tests.csproj
      publishTestResults: true
  - task: DotNetCoreCLI@2
    displayName: "dotnet test net48"
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    inputs:
      command: 'test'
      arguments: '--framework net48 --no-build'
      projects: |
        **/*Tests.csproj
      publishTestResults: true
- job: Package
  displayName: Package
  dependsOn: BuildAndTest
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '10.0.x'
      includePreviewVersions: true
  - script: |
      dotnet pack Neme.Extensions.slnx \
        --configuration Release \
        --version "1.0.0-CI-$(Build.BuildNumber)" \
        --output "$(Build.ArtifactStagingDirectory)"
    displayName: "dotnet pack"
  - task: DotNetCoreCLI@2
    displayName: "dotnet nuget push"
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '2bd7f127-944b-4d55-b863-c18d972416cd/67d0c6fc-0641-4977-8730-61fbb8b117f3'
- job: DebugPackage
  displayName: Debug Package
  dependsOn: BuildAndTest
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '10.0.x'
      includePreviewVersions: true
  - script: |
      dotnet pack Neme.Extensions.slnx \
        --configuration Debug \
        --version "1.0.0-CI-$(Build.BuildNumber)+debug" \
        --output "$(Build.ArtifactStagingDirectory)"
    displayName: "dotnet pack"
  - task: DotNetCoreCLI@2
    displayName: "dotnet nuget push"
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '2bd7f127-944b-4d55-b863-c18d972416cd/67d0c6fc-0641-4977-8730-61fbb8b117f3'
