# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'

jobs:
- job:
  displayName: "Build and test"
  strategy:
    matrix:
      windows:
        imageName: "windows-latest"
      linux:
        imageName: "ubuntu-latest"
      macOS:
        imageName: "macOS-latest"
  pool:
    vmImage: $(imageName)
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: 'test'
